# segmentation

In [32]:
import cv2
import numpy as np
import sys
import os
import matplotlib.pyplot as plt

### cv2.imread()
Second argument is a flag which specifies the way image should be read.

- cv2.IMREAD_COLOR : Loads a color image. Any transparency of image will be neglected. It is the default flag.
- cv2.IMREAD_GRAYSCALE : Loads image in grayscale mode
- cv2.IMREAD_UNCHANGED : Loads image as such including alpha channel

In [33]:
# load image at greyscale mode
image = cv2.imread("ductile_iron2-0.jpg",cv2.IMREAD_GRAYSCALE)
print(image,image.shape)

[[181 181 184 ... 167 167 170]
 [181 183 186 ... 122 120 119]
 [181 184 186 ...  98  93  88]
 ...
 [177 179 178 ... 215 215 216]
 [177 180 179 ... 215 216 216]
 [179 182 181 ... 215 216 217]] (510, 636)


In [34]:
ret, imgf = cv2.threshold(image, 0, 255, cv2.THRESH_BINARY+cv2.THRESH_OTSU)

In [37]:
imgf

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ...,   0,   0,   0],
       [255, 255, 255, ...,   0,   0,   0],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [40]:
cv2.imwrite('aaaa.png',imgf)

True

In [3]:
# define 0-255 array
hist_array = np.zeros(256,dtype=np.int32)
for i in image.ravel():
    hist_array[i]+=1
# transfer to frequency [0,1]
hist_array_f = np.zeros(256,dtype=np.float128)
for i in range(256):
    hist_array_f[i] = hist_array[i] / image.size

In [4]:
max_th=0
max_th_value = 0
rr = []
for t in range(256):
    # probability of foreground
    wf = sum([ p for p in hist_array_f[:t+1]])
    wb = sum([ p for p in hist_array_f[t+1:]])
    # varience 
    vf = 0
    vb = 0
    for i in range(t+1):
        vf += i*hist_array_f[i]
    for i in range(t+1,256):
        vb += i*hist_array_f[i]
        
    if(wf ==0 or wb ==0):
        continue
        
    vf = vf / wf 
    vb = vb / wb 
    
    # the inter-class varience
    r = wf*wb*(vf - vb)*(vf - vb)
    
    
    if r > max_th_value:
        max_th_value = r
        max_th = t

print(max_th)
    

143
